export default {
    Server: Symbol("Server"),
    Application: Symbol("Application"),
    Routes: Symbol("Routes"),
    VueInitialeService: Symbol("VueInitialeService"),
    Connexion: Symbol("Connexion"),
    FicheVueService: Symbol("FicheJeuService"),
    TransmissionFiche: Symbol("TransmissionFiche"),
    GenerateurDifferencesService: Symbol("GenerateurDifferencesService"),
    Parties: Symbol("Parties"),
    BaseDeDonnees: Symbol("BaseDeDonnees"),
    IdentificationDifferencesLibreService: Symbol("IdentificationDifferencesLibreService"),
    Donnees: Symbol("Donnees"),
    GestionTempsService: Symbol("GestionTempsService"),
    SocketService: Symbol("SocketService"),
    PartiesMultijoueur: Symbol("PartiesMultijoueur"),
    IdMultijoueurService: Symbol("IdMultiJoueur"),
    TransmissionIds: Symbol("TransmissionIds"),
};
